import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Create body with 100% vh */}
      <body className={`flex flex-col h-screen text-gray-500 ${inter.className}`}>
        {children}
        <footer className="text-center text-sm border-black border-4">
          <p>
            Built by {" "}
            <a
              href="https://github.com/bead-code"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-500"
            >
              Bead
            </a>
          </p>
        </footer>
      </body>
    </html>
  );
}
